apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: reddyashishaleti/nestjs$BUILD_NUMBER:latest
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nestjs
spec:
  selector:
    app: nodeapp 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:  
  name: strip-prefix  
  namespace: default
spec:  
  stripPrefixRegex:
    regex:
      - "/[^/]*/[^/]*"

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nestjs
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`api.ashish.net`) && PathPrefix(`/devops/availability`)
    middlewares:
    - name: strip-prefix
    kind: Rule
    services:
    - name: nestjs
      port: 80
  tls:
    certResolver: pebble

